# Dataset
ds_rate: 1
dataset_name: 'hugadb'
train_vids_file: 'Datasets/hugadb/splits/train.split1.bundle'
test_vids_file: 'Datasets/hugadb/splits/test.split1.bundle'
channel: 6
num_classes: 12
gt_path: 'Datasets/hugadb/gt_arr/'
gt_bound_path: 'Datasets/hugadb/gt_boundary_arr/'
feature_path: 'Datasets/hugadb/features/'
joint_num: 6
feature_type: 'origin'
segment_num: 64

# hyper
learning_rate: 0.0005
warmup: True
warm_epoch: 10
period_epoch: 1
num_epochs: 120
batch_size: 3


# Spatial
feat_dim: 12
spatial_dil: [1,2,4,8,16,32,64,128,256,512]
graph_layout: 'hugadb'
graph_strategy: 'spatial'
spatial_filters: 64
edge_importance_weighting: True

# Temporal
num_stages: 4
num_f_maps: 64
num_layers: 10
temporal_dil: [1,2,4,8,16,32,64,128,256,512]



